name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build libs
        run: |
          # Build workspace libs so tests can import their compiled output
          npm run -w libs/logger build || true
          npm run -w libs/metrics build || true

      - name: Run tests
        run: npm test
